### ISSUE TITLE
Error on opening

### ISSUE THREAD

**Issue by JanSzumotalski** [PlayBy/Discord-LiveBot#1]
```
'electron' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by PlayBy** [comment]
do `npm install` in the directory. I forgot to list that in the steps, but it installs everything needed.

**Comment by JanSzumotalski** [comment]
npm WARN discord.js@11.3.0 requires a peer of bufferutil@^3.0.2 but none was installed.
npm WARN discord.js@11.3.0 requires a peer of erlpack@discordapp/erlpack but none was installed.
npm WARN discord.js@11.3.0 requires a peer of node-opus@^0.2.6 but none was installed.
npm WARN discord.js@11.3.0 requires a peer of opusscript@^0.0.3 but none was installed.
npm WARN discord.js@11.3.0 requires a peer of sodium@^2.0.1 but none was installed.
npm WARN discord.js@11.3.0 requires a peer of libsodium-wrappers@^0.5.4 but none was installed.
npm WARN discord.js@11.3.0 requires a peer of uws@^0.14.5 but none was installed.

**Comment by PlayBy** [comment]
Yes that just happens. You don't need to worry about it. It should still work

**Comment by JanSzumotalski** [comment]
still same error from post #1

**Comment by PlayBy** [comment]
Are you doing the `npm install` in the correct directory?

**Comment by JanSzumotalski** [comment]
yes

**Comment by PlayBy** [comment]
ok well try doing `npm install electron`

**Comment by JanSzumotalski** [comment]
it works!
thank you!

**Comment by PlayBy** [comment]
Alright cool :). Wonder why npm install diddn't work....
