### ISSUE TITLE
How to join server?

### ISSUE THREAD

**Issue by JanSzumotalski** [PlayBy/Discord-LiveBot#2]

**Comment by PlayBy** [comment]
At this point you are unable to do a lot of things. Basically just talking and reading messages. Also bots cannot join with an invite.

**Comment by JanSzumotalski** [comment]
So... How to make my bot join server?

**Comment by PlayBy** [comment]
You use an invite link. You can create one by going to your apps page, clicking on your bot, then clicking generate oauth link.

**Comment by JanSzumotalski** [comment]
Thanks
