### ISSUE TITLE
How to:...

### ISSUE THREAD

**Issue by JanSzumotalski** [PlayBy/Discord-LiveBot#3]
How do i can:
Make emojis
Mention someone (like @someone#1234)

And also: What "Generate Invite" button does?

Sorry But it's not documented anywhere

**Comment by JanSzumotalski** [comment]
I know what Generate Invite Button does

**Comment by PlayBy** [comment]
Alright so. You make emojis like normal, there is no menu though, because as I mentioned in the last error you made, it is in development. If you want to mention someone, well you cant I guess. You have to type the actual tag.

**Comment by JanSzumotalski** [comment]
If i enter  @Someone#1234 it's just a regular text, not mention

**Comment by PlayBy** [comment]
Then i guesd you cant. Csn you stop talking in issues inless it is an issue? Only talk here if there is a bug or something.

**Comment by JanSzumotalski** [comment]
That will be very rude, but is there a forum or something?

**Comment by PlayBy** [comment]
No there is no forum. This is a single developer project that i stopped working on. Its not even close to being finished so please, if there is something you cannot do, dont put that in issues on github.

**Comment by JanSzumotalski** [comment]
ok
