### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by testforwhasonyt** [PlayBy/Discord-LiveBot#5]
I can't figure out on how to install it, Every method I try fails.

**Comment by PlayBy** [comment]
What is the error?

**Comment by PlayBy** [comment]
and when you install it, just download it with a zip and unpack it, or clone it. Then in the directory open a console and type `npm install`

**Comment by PlayBy** [comment]
Have you figured it out?

**Comment by Dylstructor** [comment]
Same problem here. i when i do npm install it says

npm WARN discord.js@11.3.0 requires a peer of bufferutil@^3.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of node-opus@^0.2.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of opusscript@^0.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of sodium@^2.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of libsodium-wrappers@^0.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of uws@^0.14.5 but none is installed. You must install peer dependencies yourself.

**Comment by PlayBy** [comment]
Those are just warnings. That happens and shouldn't cause problems.

**Comment by Dylstructor** [comment]
No worries ineeded to install electron 

 really cool program!

**Comment by PlayBy** [comment]
Great glad you could fix it! And thanks :D
